name: Android Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check Runner
        run: echo Runner is working

      - name: Check Android Device
        run: adb devices
